#!/bin/sh

sxhkd &
redshift &
set_time &
$HOME/.config/polybar/launch.sh &
feh --bg-fill $HOME/photos/bg.jpg
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV
bspc config border_width 2

bspc config window_gap 4
bspc config split_ratio 0.50

bspc config click_to_focus true
bspc config pointer_modifier super
bspc config pointer_action1 move

bspc rule -a Xfe state=floating
bspc rule -a Zathura state=tiled
